const dummyData = [
  {
    id: 1,
    location: "Parking gateway",
    connectedNodes: 5,
    active: "active",
    color: "#03A60E",
  },
  {
    id: 2,
    location: "Kitchen",
    connectedNodes: 3,
    active: "standby",
    color: "#F2E205",
  },
  {
    id: 3,
    location: "Bedroom",
    connectedNodes: 2,
    active: "standby",
    color: "#F2E205",
  },
  {
    id: 4,
    location: "Admin Building",
    connectedNodes: 2,
    active: "active",
    color: "#FF0000",
  },
  {
    id: 5,
    location: "Admin Building",
    connectedNodes: 2,
    active: "active",
    color: "#03A60E",
  },
  {
    id: 6,
    location: "Admin Building",
    connectedNodes: 2,
    active: "standby",
    color: "#F2E205",
  },
  {
    id: 7,
    location: "Admin Building",
    connectedNodes: 2,
    active: "inactive",
    color: "#FF0000",
  },
  {
    id: 8,
    location: "Admin Building",
    connectedNodes: 2,
    active: "inactive",
    color: "#FF0000",
  },
  {
    id: 9,
    location: "Admin Building",
    connectedNodes: 2,
    active: "active",
    color: "#03A60E",
  },

  {
    id: 10,
    location: "Admin Building",
    connectedNodes: 2,
    active: "active",
    color: "#03A60E",
  },
  {
    id: 11,
    location: "Admin Building",
    connectedNodes: 2,
    active: "inactive",
    color: "#FF0000",
  },
  {
    id: 12,
    location: "Operations Building",
    connectedNodes: 2,
    active: "active",
    color: "#03A60E",
  },
  {
    id: 13,
    location: "Op II Building",
    connectedNodes: 2,
    active: "active",
    color: "#03A60E",
  },
  {
    id: 14,
    location: "Op I Building",
    connectedNodes: 2,
    active: "active",
    color: "#03A60E",
  },
];

export default dummyData;
