const nodeInfo = {
  critical_energy: "Critical Energy",
  critical_fuel: "Critical Fuel",
  critical_humidity: "Critical Humidity",
  critical_power: "Critical Power",
  critical_temp: "Critical Temperature",
  energy_watt_hr: "Energy (Watt-Hour)",
  fuel_lt: "Fuel (Liters)",
  humidity_g_m3: "Humidity (g/m³)",
  id: "ID",
  max_energy: "Max Energy",
  max_fuel: "Max Fuel",
  max_humidity: "Max Humidity",
  max_power: "Max Power",
  max_temp: "Max Temperature",
  meter_name: "Meter Name",
  min_energy: "Min Energy",
  min_fuel: "Min Fuel",
  min_humidity: "Min Humidity",
  min_power: "Min Power",
  min_temp: "Min Temperature",
  moisture_g_m3: "Moisture (g/m³)",
  name_of_table: "Table Name",
  node_mac: "Node MAC",
  power_watt: "Power (Watt)",
  temperature_c: "Temperature (°C)",
  timestamp: "Timestamp",
  current_a: "Current (Ampere)",
  co2_p: "CO2 (ppm)",
  aud_db: "Audio (decibal)",
  lux_l: "Illuminance (LUX)",
  min_co2: "Min CO2",
  max_co2: "Max CO2",
  critical_co2: "Critical CO2",
  min_lux: "Min Illuminance",
  max_lux: "Max Illuminance",
  critical_lux: "Critical Illuminance",
  type: "Sensor Type",
};


// const node={
//   english:{
//     const nodeInfo = {
//       critical_energy: "Critical Energy",
//       critical_fuel: "Critical Fuel",
//       critical_humidity: "Critical Humidity",
//       critical_power: "Critical Power",
//       critical_temp: "Critical Temperature",
//       energy_watt_hr: "Energy (Watt-Hour)",
//       fuel_lt: "Fuel (Liters)",
//       humidity_g_m3: "Humidity (g/m³)",
//       id: "ID",
//       max_energy: "Max Energy",
//       max_fuel: "Max Fuel",
//       max_humidity: "Max Humidity",
//       max_power: "Max Power",
//       max_temp: "Max Temperature",
//       meter_name: "Meter Name",
//       min_energy: "Min Energy",
//       min_fuel: "Min Fuel",
//       min_humidity: "Min Humidity",
//       min_power: "Min Power",
//       min_temp: "Min Temperature",
//       moisture_g_m3: "Moisture (g/m³)",
//       name_of_table: "Table Name",
//       node_mac: "Node MAC",
//       power_watt: "Power (Watt)",
//       temperature_c: "Temperature (°C)",
//       timestamp: "Timestamp",
//       current_a: "Current (Ampere)",
//       co2_p: "CO2 (ppm)",
//       aud_db: "Audio (decibal)",
//       lux_l: "Illuminance (LUX)",
//       min_co2: "Min CO2",
//       max_co2: "Max CO2",
//       critical_co2: "Critical CO2",
//       min_lux: "Min Illuminance",
//       max_lux: "Max Illuminance",
//       critical_lux: "Critical Illuminance",
//       type: "Sensor Type",
//     },
//     japanese:{
//       const nodeInfo = {
//         critical_energy: "Critical Energy",
//         critical_fuel: "Critical Fuel",
//         critical_humidity: "Critical Humidity",
//         critical_power: "Critical Power",
//         critical_temp: "Critical Temperature",
//         energy_watt_hr: "Energy (Watt-Hour)",
//         fuel_lt: "Fuel (Liters)",
//         humidity_g_m3: "Humidity (g/m³)",
//         id: "ID",
//         max_energy: "Max Energy",
//         max_fuel: "Max Fuel",
//         max_humidity: "Max Humidity",
//         max_power: "Max Power",
//         max_temp: "Max Temperature",
//         meter_name: "Meter Name",
//         min_energy: "Min Energy",
//         min_fuel: "Min Fuel",
//         min_humidity: "Min Humidity",
//         min_power: "Min Power",
//         min_temp: "Min Temperature",
//         moisture_g_m3: "Moisture (g/m³)",
//         name_of_table: "Table Name",
//         node_mac: "Node MAC",
//         power_watt: "Power (Watt)",
//         temperature_c: "Temperature (°C)",
//         timestamp: "Timestamp",
//         current_a: "Current (Ampere)",
//         co2_p: "CO2 (ppm)",
//         aud_db: "Audio (decibal)",
//         lux_l: "Illuminance (LUX)",
//         min_co2: "Min CO2",
//         max_co2: "Max CO2",
//         critical_co2: "Critical CO2",
//         min_lux: "Min Illuminance",
//         max_lux: "Max Illuminance",
//         critical_lux: "Critical Illuminance",
//         type: "Sensor Type",
//       };
      
//     }    
//   }
// }
export default nodeInfo;
